sudo: false
language: node_js
node_js:
  - '0.12'

addons:
  firefox: "36.0"

cache:
  directories:
    - node_modules

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm install -g webdriver-manager
  - npm install -g codeclimate-test-reporter
  - npm install -g coveralls
  - npm install
  - webdriver-manager update --standalone

before_script:
  - phantomjs -w > /dev/null &
  - sleep 2
  - webdriver-manager start > /dev/null &
  - sleep 2
  - npm start &
  - sleep 2

script: npm run coverage

after_script:
  - cat ./coverage/lcov.info | coveralls
  - codeclimate < ./coverage/lcov.info
